// templates/frontend/nextjs/app/page.tsx
'use client';

import { useState, FormEvent } from 'react';

export default function Home() {
  const [number, setNumber] = useState<string>('');
  const [result, setResult] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError(null);
    setResult(null);

    try {
      const response = await fetch('http://localhost:8000/api/multiply', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ number: parseFloat(number) }),
      });

      if (!response.ok) {
        throw new Error('Network response was not ok');
      }

      const data = await response.json();
      setResult(data.result);
    } catch (err: unknown) {
      setError((err as Error).message);
    }
  };

  return (
    <main style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>Multiplier App</h1>
      <form onSubmit={handleSubmit} style={{ marginBottom: '1rem' }}>
        <label htmlFor="numberInput" style={{ display: 'block', marginBottom: '0.5rem' }}>
          Enter a number:
        </label>
        <input
          id="numberInput"
          type="number"
          step="any"
          value={number}
          onChange={(e) => setNumber(e.target.value)}
          required
          style={{ padding: '0.5rem', marginRight: '0.5rem' }}
        />
        <button type="submit" style={{ padding: '0.5rem 1rem' }}>
          Multiply by 2
        </button>
      </form>

      {result !== null && (
        <div style={{ marginTop: '1rem', padding: '1rem', backgroundColor: '#e0ffe0', border: '1px solid #00cc00' }}>
          <strong>Result:</strong> {result}
        </div>
      )}

      {error && (
        <div style={{ marginTop: '1rem', padding: '1rem', backgroundColor: '#ffe0e0', border: '1px solid #cc0000' }}>
          <strong>Error:</strong> {error}
        </div>
      )}
    </main>
  );
}

// templates/frontend/svelte/src/App.svelte
<script lang="ts">
  let number: string = '';
  let result: number | null = null;
  let error: string | null = null;

  async function handleSubmit() {
    error = null;
    result = null;

    try {
      const response = await fetch('http://localhost:8000/api/multiply', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ number: parseFloat(number) }),
      });

      if (!response.ok) {
        throw new Error('Network response was not ok');
      }

      const data = await response.json();
      result = data.result;
    } catch (err: unknown) {
      error = (err as Error).message;
    }
  }
</script>

<main style="padding: 2rem; font-family: sans-serif;">
  <h1>Multiplier App (Svelte)</h1>
  <form on:submit|preventDefault={handleSubmit} style="margin-bottom: 1rem;">
    <label for="numberInput" style="display: block; margin-bottom: 0.5rem;">
      Enter a number:
    </label>
    <input
      id="numberInput"
      type="number"
      step="any"
      bind:value={number}
      required
      style="padding: 0.5rem; margin-right: 0.5rem;"
    />
    <button type="submit" style="padding: 0.5rem 1rem;">
      Multiply by 2
    </button>
  </form>

  {#if result !== null}
    <div style="margin-top: 1rem; padding: 1rem; background-color: #e0ffe0; border: 1px solid #00cc00;">
      <strong>Result:</strong> {result}
    </div>
  {/if}

  {#if error}
    <div style="margin-top: 1rem; padding: 1rem; background-color: #ffe0e0; border: 1px solid #cc0000;">
      <strong>Error:</strong> {error}
    </div>
  {/if}
</main>
